/*
 * This file is generated by jOOQ.
 */
package ru.dsoccer.jooq.entities.tables.daos;


import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ru.dsoccer.jooq.entities.tables.Company;
import ru.dsoccer.jooq.entities.tables.records.CompanyRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyDao extends DAOImpl<CompanyRecord, ru.dsoccer.jooq.entities.tables.pojos.Company, Long> {

    /**
     * Create a new CompanyDao without any configuration
     */
    public CompanyDao() {
        super(Company.COMPANY, ru.dsoccer.jooq.entities.tables.pojos.Company.class);
    }

    /**
     * Create a new CompanyDao with an attached configuration
     */
    public CompanyDao(Configuration configuration) {
        super(Company.COMPANY, ru.dsoccer.jooq.entities.tables.pojos.Company.class, configuration);
    }

    @Override
    public Long getId(ru.dsoccer.jooq.entities.tables.pojos.Company object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.dsoccer.jooq.entities.tables.pojos.Company> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Company.COMPANY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<ru.dsoccer.jooq.entities.tables.pojos.Company> fetchById(Long... values) {
        return fetch(Company.COMPANY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public ru.dsoccer.jooq.entities.tables.pojos.Company fetchOneById(Long value) {
        return fetchOne(Company.COMPANY.ID, value);
    }

    /**
     * Fetch records that have <code>COMPANY_NAME BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.dsoccer.jooq.entities.tables.pojos.Company> fetchRangeOfCompanyName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Company.COMPANY.COMPANY_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>COMPANY_NAME IN (values)</code>
     */
    public List<ru.dsoccer.jooq.entities.tables.pojos.Company> fetchByCompanyName(String... values) {
        return fetch(Company.COMPANY.COMPANY_NAME, values);
    }
}
