/*
 * This file is generated by jOOQ.
 */
package ru.dsoccer.jooq.entities.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String companyName;

    public Company() {}

    public Company(Company value) {
        this.id = value.id;
        this.companyName = value.companyName;
    }

    public Company(
        Long   id,
        String companyName
    ) {
        this.id = id;
        this.companyName = companyName;
    }

    /**
     * Getter for <code>COMPANY.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>COMPANY.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>COMPANY.COMPANY_NAME</code>.
     */
    public String getCompanyName() {
        return this.companyName;
    }

    /**
     * Setter for <code>COMPANY.COMPANY_NAME</code>.
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Company (");

        sb.append(id);
        sb.append(", ").append(companyName);

        sb.append(")");
        return sb.toString();
    }
}
