/*
 * This file is generated by jOOQ.
 */
package ru.dsoccer.jooq.entities.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String personName;
    private Long   companyId;

    public Person() {}

    public Person(Person value) {
        this.id = value.id;
        this.personName = value.personName;
        this.companyId = value.companyId;
    }

    public Person(
        Long   id,
        String personName,
        Long   companyId
    ) {
        this.id = id;
        this.personName = personName;
        this.companyId = companyId;
    }

    /**
     * Getter for <code>PERSON.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>PERSON.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>PERSON.PERSON_NAME</code>.
     */
    public String getPersonName() {
        return this.personName;
    }

    /**
     * Setter for <code>PERSON.PERSON_NAME</code>.
     */
    public void setPersonName(String personName) {
        this.personName = personName;
    }

    /**
     * Getter for <code>PERSON.COMPANY_ID</code>.
     */
    public Long getCompanyId() {
        return this.companyId;
    }

    /**
     * Setter for <code>PERSON.COMPANY_ID</code>.
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Person (");

        sb.append(id);
        sb.append(", ").append(personName);
        sb.append(", ").append(companyId);

        sb.append(")");
        return sb.toString();
    }
}
