graphql:
  servlet:
    max-query-depth: 5
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
      - name: Bank account mutation query
        query: classpath:playground/bank_account_mutation_query.graphql


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql
    username: root
    password: root
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 3MB