graphql:
  servlet:
    max-query-depth: 5
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
      - name: Bank account mutation query
        query: classpath:playground/bank_account_mutation_query.graphql
#    enabled: false