spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proddb
    username: postgres
    password: postgres
    initialization-mode: never  #put never if db already exists
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

