/*
 * This file is generated by jOOQ.
 */
package ru.dsoccer.jooq.entities;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.dsoccer.jooq.entities.tables.Company;
import ru.dsoccer.jooq.entities.tables.Person;
import ru.dsoccer.jooq.entities.tables.records.CompanyRecord;
import ru.dsoccer.jooq.entities.tables.records.PersonRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CompanyRecord> CONSTRAINT_6 = Internal.createUniqueKey(Company.COMPANY, DSL.name("CONSTRAINT_6"), new TableField[] { Company.COMPANY.ID }, true);
    public static final UniqueKey<PersonRecord> CONSTRAINT_8 = Internal.createUniqueKey(Person.PERSON, DSL.name("CONSTRAINT_8"), new TableField[] { Person.PERSON.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PersonRecord, CompanyRecord> FK8AKPPQVVI9WA7BB0KVYV0TLU9 = Internal.createForeignKey(Person.PERSON, DSL.name("FK8AKPPQVVI9WA7BB0KVYV0TLU9"), new TableField[] { Person.PERSON.COMPANY_ID }, Keys.CONSTRAINT_6, new TableField[] { Company.COMPANY.ID }, true);
}
