/*
 * This file is generated by jOOQ.
 */
package ru.dsoccer.jooq.entities;


import ru.dsoccer.jooq.entities.tables.Company;
import ru.dsoccer.jooq.entities.tables.Person;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>COMPANY</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>PERSON</code>.
     */
    public static final Person PERSON = Person.PERSON;
}
