spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bet
    username: root
    password: root
    initialization-mode: never
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true